***

Important urls :


https://www.geeksforgeeks.org/data-visualization/matplotlib-step-by-step-guide/
https://www.kaggle.com/datasets/ankulsharma150/food-order-cost-and-profit-analysis?resource=download
https://www.storytellingwithdata.com/book/downloads
https://amanxai.com/2024/06/11/data-cleaning-methods-you-should-know/

In [209]:
import pandas as pd
import numpy as np
from datetime import date, datetime, timedelta
import math

In [210]:
df = pd.DataFrame([[1, 4], [2, 5], [3, 6], [4, 7]], columns = ['A', 'B'])
df.describe(percentiles = [1/3, 2/3])

              A         B
count  4.000000  4.000000
mean   2.500000  5.500000
std    1.290994  1.290994
min    1.000000  4.000000
33.3%  2.000000  5.000000
50%    2.500000  5.500000
66.7%  3.000000  6.000000
max    4.000000  7.000000

In [211]:
num_customers = 100
np.random.seed(0)

In [212]:
df_bank = pd.DataFrame(columns = ["CustomerID"])
df_bank["CustomerID"] = [str(x) for x in np.arange(num_customers)]
df_bank

   CustomerID
0           0
1           1
2           2
3           3
4           4
..        ...
95         95
96         96
97         97
98         98
99         99

[100 rows x 1 columns]

In [213]:
start = datetime(1950, 1, 1)
end = datetime(2024, 1, 1)
numdays = (end - start).days
random_days = np.random.randint(0, numdays, size = num_customers)

In [214]:
df_bank["BirthDate"] = start + pd.to_timedelta(random_days, unit='D')
df_bank

   CustomerID  BirthDate
0           0 1957-06-25
1           1 1979-07-27
2           2 1976-12-15
3           3 2003-10-18
4           4 1985-12-06
..        ...        ...
95         95 1975-09-23
96         96 1989-03-09
97         97 1960-09-23
98         98 1975-08-17
99         99 1999-06-21

[100 rows x 2 columns]

In [215]:
# override the birthdate column to be a string format of the date
df_bank["BirthDate"] = df_bank["BirthDate"].dt.strftime('%Y-%m-%d')
df_bank

   CustomerID   BirthDate
0           0  1957-06-25
1           1  1979-07-27
2           2  1976-12-15
3           3  2003-10-18
4           4  1985-12-06
..        ...         ...
95         95  1975-09-23
96         96  1989-03-09
97         97  1960-09-23
98         98  1975-08-17
99         99  1999-06-21

[100 rows x 2 columns]

In [216]:
def make_ssn_string(num):
    ssn_str = f'{num:09}'
    return ssn_str[0:3] + "-" + ssn_str[3:5] + "-" + ssn_str[5:9]
ssn_vector_func = np.vectorize(make_ssn_string)
df_bank["SSN"] = ssn_vector_func(np.random.randint(0, 999999999, size = num_customers))
df_bank

   CustomerID   BirthDate          SSN
0           0  1957-06-25  530-47-1866
1           1  1979-07-27  682-76-9175
2           2  1976-12-15  377-98-9839
3           3  2003-10-18  474-05-7613
4           4  1985-12-06  750-55-5509
..        ...         ...          ...
95         95  1975-09-23  607-97-1651
96         96  1989-03-09  870-80-0364
97         97  1960-09-23  773-33-2797
98         98  1975-08-17  846-64-7054
99         99  1999-06-21  855-54-7744

[100 rows x 3 columns]

In [217]:
df_bank["AccountID"] = np.random.randint(0, num_customers, size = num_customers)
df_bank

   CustomerID   BirthDate          SSN  AccountID
0           0  1957-06-25  530-47-1866          4
1           1  1979-07-27  682-76-9175         67
2           2  1976-12-15  377-98-9839         11
3           3  2003-10-18  474-05-7613         86
4           4  1985-12-06  750-55-5509         77
..        ...         ...          ...        ...
95         95  1975-09-23  607-97-1651         36
96         96  1989-03-09  870-80-0364          0
97         97  1960-09-23  773-33-2797         75
98         98  1975-08-17  846-64-7054         34
99         99  1999-06-21  855-54-7744         69

[100 rows x 4 columns]

In [218]:
# add a random number of days to the birthdate to get the account opened date lower=0 upper=80 years
random_days = np.random.randint(0, 365 * 80, size = num_customers)
df_bank["AccountOpened"] = (pd.to_datetime(df_bank["BirthDate"]) + pd.to_timedelta(random_days, unit='D')).dt.strftime('%Y-%m-%d')
df_bank

   CustomerID   BirthDate          SSN  AccountID AccountOpened
0           0  1957-06-25  530-47-1866          4    1959-12-06
1           1  1979-07-27  682-76-9175         67    2039-02-20
2           2  1976-12-15  377-98-9839         11    2019-03-25
3           3  2003-10-18  474-05-7613         86    2004-03-02
4           4  1985-12-06  750-55-5509         77    2059-05-05
..        ...         ...          ...        ...           ...
95         95  1975-09-23  607-97-1651         36    2011-07-24
96         96  1989-03-09  870-80-0364          0    2054-11-01
97         97  1960-09-23  773-33-2797         75    1993-09-16
98         98  1975-08-17  846-64-7054         34    2032-12-25
99         99  1999-06-21  855-54-7744         69    2025-06-24

[100 rows x 5 columns]

In [219]:
df_bank.loc[0, "BirthDate"] = "1980"
df_bank.loc[1, "BirthDate"] = "no date"
df_bank.loc[2, "AccountID"] = np.nan
df_bank

   CustomerID   BirthDate          SSN  AccountID AccountOpened
0           0        1980  530-47-1866        4.0    1959-12-06
1           1     no date  682-76-9175       67.0    2039-02-20
2           2  1976-12-15  377-98-9839        NaN    2019-03-25
3           3  2003-10-18  474-05-7613       86.0    2004-03-02
4           4  1985-12-06  750-55-5509       77.0    2059-05-05
..        ...         ...          ...        ...           ...
95         95  1975-09-23  607-97-1651       36.0    2011-07-24
96         96  1989-03-09  870-80-0364        0.0    2054-11-01
97         97  1960-09-23  773-33-2797       75.0    1993-09-16
98         98  1975-08-17  846-64-7054       34.0    2032-12-25
99         99  1999-06-21  855-54-7744       69.0    2025-06-24

[100 rows x 5 columns]

In [220]:
df_bank["AccountType"] = np.random.choice(["checking", "savings", "cd"], size = num_customers)
df_bank

   CustomerID   BirthDate          SSN  AccountID AccountOpened AccountType
0           0        1980  530-47-1866        4.0    1959-12-06    checking
1           1     no date  682-76-9175       67.0    2039-02-20          cd
2           2  1976-12-15  377-98-9839        NaN    2019-03-25    checking
3           3  2003-10-18  474-05-7613       86.0    2004-03-02          cd
4           4  1985-12-06  750-55-5509       77.0    2059-05-05          cd
..        ...         ...          ...        ...           ...         ...
95         95  1975-09-23  607-97-1651       36.0    2011-07-24    checking
96         96  1989-03-09  870-80-0364        0.0    2054-11-01          cd
97         97  1960-09-23  773-33-2797       75.0    1993-09-16          cd
98         98  1975-08-17  846-64-7054       34.0    2032-12-25     savings
99         99  1999-06-21  855-54-7744       69.0    2025-06-24    checking

[100 rows x 6 columns]

In [221]:
# Replaces row 99 (last row) of df_bank with row 0 (first row) from df
df_bank.loc[num_customers - 1] = df.loc[0]
df_bank

   CustomerID   BirthDate          SSN  AccountID AccountOpened AccountType
0           0        1980  530-47-1866        4.0    1959-12-06    checking
1           1     no date  682-76-9175       67.0    2039-02-20          cd
2           2  1976-12-15  377-98-9839        NaN    2019-03-25    checking
3           3  2003-10-18  474-05-7613       86.0    2004-03-02          cd
4           4  1985-12-06  750-55-5509       77.0    2059-05-05          cd
..        ...         ...          ...        ...           ...         ...
95         95  1975-09-23  607-97-1651       36.0    2011-07-24    checking
96         96  1989-03-09  870-80-0364        0.0    2054-11-01          cd
97         97  1960-09-23  773-33-2797       75.0    1993-09-16          cd
98         98  1975-08-17  846-64-7054       34.0    2032-12-25     savings
99        NaN         NaN          NaN        NaN           NaN         NaN

[100 rows x 6 columns]

In [222]:
df_bank.to_csv("bank_customers.csv", index=False)

In [223]:
df_bank_loaded = pd.read_csv("bank_customers.csv")

In [224]:
# The first few rows
df_bank_loaded.iloc[0:5]

   CustomerID   BirthDate          SSN  AccountID AccountOpened AccountType
0         0.0        1980  530-47-1866        4.0    1959-12-06    checking
1         1.0     no date  682-76-9175       67.0    2039-02-20          cd
2         2.0  1976-12-15  377-98-9839        NaN    2019-03-25    checking
3         3.0  2003-10-18  474-05-7613       86.0    2004-03-02          cd
4         4.0  1985-12-06  750-55-5509       77.0    2059-05-05          cd

In [ ]:
# Format check to filter valid dates
valid_dates = pd.to_datetime(df_bank_loaded["BirthDate"], format='%Y-%m-%d', errors='coerce')
df_bank_datefix = df_bank_loaded[valid_dates.notna()].copy()

# Convert AccountOpened to datetime as well
df_bank_datefix["AccountOpened"] = pd.to_datetime(df_bank_datefix["AccountOpened"], format='%Y-%m-%d', errors='coerce')
df_bank_datefix["BirthDate"] = pd.to_datetime(df_bank_datefix["BirthDate"], format='%Y-%m-%d')
df_bank_datefix

    CustomerID   BirthDate          SSN  AccountID AccountOpened AccountType
2          2.0  1976-12-15  377-98-9839        NaN    2019-03-25    checking
3          3.0  2003-10-18  474-05-7613       86.0    2004-03-02          cd
4          4.0  1985-12-06  750-55-5509       77.0    2059-05-05          cd
5          5.0  2008-02-29  671-43-0485       75.0    2025-05-03    checking
6          6.0  1975-04-05  288-62-9296       56.0    2048-09-21     savings
..         ...         ...          ...        ...           ...         ...
94        94.0  1969-03-14  958-12-8308        5.0    2037-04-03     savings
95        95.0  1975-09-23  607-97-1651       36.0    2011-07-24    checking
96        96.0  1989-03-09  870-80-0364        0.0    2054-11-01          cd
97        97.0  1960-09-23  773-33-2797       75.0    1993-09-16          cd
98        98.0  1975-08-17  846-64-7054       34.0    2032-12-25     savings

[97 rows x 6 columns]

In [226]:
# Find all duplicate rows and show their original index
df_bank_datefix_nonull = df_bank_datefix.dropna()
duplicate_rows = df_bank_datefix_nonull[df_bank_datefix_nonull.duplicated(keep=False)]
print(f"Number of duplicate rows: {len(duplicate_rows)}")
print(f"\nRow indices of duplicate rows:")
print(duplicate_rows.index.tolist())
df_bank_datefix_nonull_no_duplicates = df_bank_datefix_nonull.drop_duplicates()
# Display the full duplicate rows
duplicate_rows

Number of duplicate rows: 0

Row indices of duplicate rows:
[]

Empty DataFrame
Columns: [CustomerID, BirthDate, SSN, AccountID, AccountOpened, AccountType]
Index: []

In [227]:
df_bank_datefix_nonull_no_duplicates

    CustomerID   BirthDate          SSN  AccountID AccountOpened AccountType
3          3.0  2003-10-18  474-05-7613       86.0    2004-03-02          cd
4          4.0  1985-12-06  750-55-5509       77.0    2059-05-05          cd
5          5.0  2008-02-29  671-43-0485       75.0    2025-05-03    checking
6          6.0  1975-04-05  288-62-9296       56.0    2048-09-21     savings
7          7.0  2016-06-18  593-49-1249       16.0    2087-07-24     savings
..         ...         ...          ...        ...           ...         ...
94        94.0  1969-03-14  958-12-8308        5.0    2037-04-03     savings
95        95.0  1975-09-23  607-97-1651       36.0    2011-07-24    checking
96        96.0  1989-03-09  870-80-0364        0.0    2054-11-01          cd
97        97.0  1960-09-23  773-33-2797       75.0    1993-09-16          cd
98        98.0  1975-08-17  846-64-7054       34.0    2032-12-25     savings

[96 rows x 6 columns]

In [228]:
# Check for duplicate AccountIDs
duplicate_mask = df_bank_datefix_nonull_no_duplicates['AccountID'].duplicated(keep=False)
duplicate_account_ids = df_bank_datefix_nonull_no_duplicates[duplicate_mask]

if len(duplicate_account_ids) > 0:
    print(f"Total rows with duplicate AccountIDs: {len(duplicate_account_ids)}")
    print(f"Unique AccountID values that are duplicated: {duplicate_account_ids['AccountID'].nunique()}")
    
    # Show counts for each duplicate AccountID
    print(f"\nCount of occurrences for each duplicate AccountID:")
    print(duplicate_account_ids['AccountID'].value_counts())
    
    # Show all rows with duplicate AccountIDs (sorted by AccountID for easier viewing)
    print(f"\nAll rows with duplicate AccountIDs:")
    duplicate_account_ids.sort_values('AccountID')
else:
    print("No duplicate AccountIDs found - all AccountIDs are unique!")

Total rows with duplicate AccountIDs: 62
Unique AccountID values that are duplicated: 29

Count of occurrences for each duplicate AccountID:
AccountID
34.0    3
24.0    3
61.0    3
3.0     3
44.0    2
9.0     2
39.0    2
46.0    2
53.0    2
23.0    2
27.0    2
10.0    2
35.0    2
67.0    2
88.0    2
86.0    2
11.0    2
75.0    2
41.0    2
79.0    2
71.0    2
31.0    2
85.0    2
32.0    2
33.0    2
83.0    2
29.0    2
56.0    2
54.0    2
Name: count, dtype: int64

All rows with duplicate AccountIDs:

In [229]:
# Remove duplicate AccountIDs, keeping the first occurrence of each AccountID
df_bank_datefix_nonull_no_duplicates_unique_accounts = df_bank_datefix_nonull_no_duplicates.drop_duplicates(subset=['AccountID'], keep='first')
df_bank_datefix_nonull_no_duplicates_unique_accounts

    CustomerID   BirthDate          SSN  AccountID AccountOpened AccountType
3          3.0  2003-10-18  474-05-7613       86.0    2004-03-02          cd
4          4.0  1985-12-06  750-55-5509       77.0    2059-05-05          cd
5          5.0  2008-02-29  671-43-0485       75.0    2025-05-03    checking
6          6.0  1975-04-05  288-62-9296       56.0    2048-09-21     savings
7          7.0  2016-06-18  593-49-1249       16.0    2087-07-24     savings
..         ...         ...          ...        ...           ...         ...
88        88.0  1962-02-07  327-09-3267       97.0    1989-10-03          cd
90        90.0  1969-06-18  395-31-7064       34.0    2010-12-28    checking
94        94.0  1969-03-14  958-12-8308        5.0    2037-04-03     savings
95        95.0  1975-09-23  607-97-1651       36.0    2011-07-24    checking
96        96.0  1989-03-09  870-80-0364        0.0    2054-11-01          cd

[63 rows x 6 columns]

In [230]:

# Create explicit copy to avoid warning
df_bank_datefix_nonull_no_duplicates_unique_accounts = df_bank_datefix_nonull_no_duplicates_unique_accounts.copy()

# Add Age column
df_bank_datefix_nonull_no_duplicates_unique_accounts['Age'] = (pd.to_datetime(date.today()) - pd.to_datetime(df_bank_datefix_nonull_no_duplicates_unique_accounts['BirthDate'])).dt.days / 365.25

# Calculate statistics (rounded down)
mean_age = math.floor(df_bank_datefix_nonull_no_duplicates_unique_accounts['Age'].mean())
median_age = math.floor(df_bank_datefix_nonull_no_duplicates_unique_accounts['Age'].median())
mode_age = math.floor(df_bank_datefix_nonull_no_duplicates_unique_accounts['Age'].mode()[0])

print(f"Mean customer age: {mean_age}")
print(f"Median customer age: {median_age}")
print(f"Mode customer age: {mode_age}")

Mean customer age: 38
Median customer age: 35
Mode customer age: 2

In [231]:
# Calculate IQR
Q1 = df_bank_datefix_nonull_no_duplicates_unique_accounts['Age'].quantile(0.25)
Q3 = df_bank_datefix_nonull_no_duplicates_unique_accounts['Age'].quantile(0.75)
IQR = Q3 - Q1

# Define outlier boundaries
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print(f"Q1 (25th percentile): {Q1:.2f}")
print(f"Q3 (75th percentile): {Q3:.2f}")
print(f"IQR: {IQR:.2f}")
print(f"Lower bound (Q1 - 1.5*IQR): {lower_bound:.2f}")
print(f"Upper bound (Q3 + 1.5*IQR): {upper_bound:.2f}")

# Find outliers
outliers = df_bank_datefix_nonull_no_duplicates_unique_accounts[
    (df_bank_datefix_nonull_no_duplicates_unique_accounts['Age'] < lower_bound) | 
    (df_bank_datefix_nonull_no_duplicates_unique_accounts['Age'] > upper_bound)
]

print(f"\nNumber of outliers: {len(outliers)}")

if len(outliers) > 0:
    print(f"\nOutlier details:")
    print(outliers[['Age', 'BirthDate', 'AccountType']].sort_values('Age'))
    
    # Count outliers by type
    print(f"\nOutliers by type:")
    print(f"  Very young (age < {lower_bound:.2f}): {len(outliers[outliers['Age'] < lower_bound])}")
    print(f"  Very old (age > {upper_bound:.2f}): {len(outliers[outliers['Age'] > upper_bound])}")
else:
    print("No outliers found!")

Q1 (25th percentile): 23.89
Q3 (75th percentile): 55.93
IQR: 32.04
Lower bound (Q1 - 1.5*IQR): -24.17
Upper bound (Q3 + 1.5*IQR): 103.99

Number of outliers: 0
No outliers found!

In [232]:
# Step 1: One-hot encode AccountType
one_hot = pd.get_dummies(df_bank_datefix_nonull_no_duplicates_unique_accounts["AccountType"])

# Step 2: Join to original dataframe (replace df2 with your actual dataframe name)
df_bank_with_onehot = df_bank_datefix_nonull_no_duplicates_unique_accounts.join(one_hot)

# Step 3: Display to see the result
df_bank_with_onehot.iloc[0:5]

# Step 4: Convert to integers
df_bank_with_onehot[['checking', 'savings', 'cd']] = df_bank_with_onehot[['checking', 'savings', 'cd']].astype(int)

# Step 5: Verify
df_bank_with_onehot[['AccountType', 'checking', 'savings', 'cd']].head()

  AccountType  checking  savings  cd
3          cd         0        0   1
4          cd         0        0   1
5    checking         1        0   0
6     savings         0        1   0
7     savings         0        1   0

In [233]:
#Create a copy for analysis
df_check = df_bank_with_onehot.copy()

#Create a new column for the age at which the account was opened
df_check['AgeAtAccountOpened'] = (df_check['AccountOpened'] - df_check['BirthDate']).dt.days / 365.25

# Check 1: Accounts opened in the future
future_accounts = df_check[df_check['AccountOpened'] > pd.to_datetime(date.today())]
print(f"Number of accounts opened in the future: {len(future_accounts)}")
if len(future_accounts) > 0:
    print(future_accounts[['BirthDate', 'AccountOpened', 'Age', 'AccountType']].head(10))


# Check 2: Accounts opened before birth
accounts_before_birth = df_check[df_check['AccountOpened'] <  df_check['BirthDate']]
print(f"\n2. Accounts opened before birth: {len(accounts_before_birth)}")
if len(accounts_before_birth) > 0:
    print(accounts_before_birth[['BirthDate', 'AccountOpened', 'Age', 'AccountType']].head(10))

#Check 3: Very young childrens (under 5) opening accounts
young_children = df_check[df_check['AgeAtAccountOpened'] < 5]
print(f"\n3. Very young children opening accounts: {len(young_children)}")
if len(young_children) > 0:
    print(young_children[['BirthDate', 'AccountOpened', 'Age', 'AccountType']].head(10))

#Check 4: Very old people (over 120) opening accounts
old_people = df_check[df_check['AgeAtAccountOpened'] > 120]
print(f"\n4. Very old people opening accounts: {len(old_people)}")
if len(old_people) > 0:
    print(old_people[['BirthDate', 'AccountOpened', 'Age', 'AccountType']].head(10))


# Check 5: Summary statistics
print(f"\n5. Summary Statistics:")
print(f"   Age when account opened - Min: {df_check['AgeAtAccountOpened'].min():.2f} years")
print(f"   Age when account opened - Max: {df_check['AgeAtAccountOpened'].max():.2f} years")
print(f"   Age when account opened - Mean: {df_check['AgeAtAccountOpened'].mean():.2f} years")

/var/folders/yy/xrr6737d07b4bxk9rqk356480000gp/T/ipykernel_23227/2256712896.py:5: PerformanceWarning: Adding/subtracting object-dtype array to DatetimeArray not vectorized.
  df_check['AgeAtAccountOpened'] = (df_check['AccountOpened'] - df_check['BirthDate']).dt.days / 365.25

TypeError: unsupported operand type(s) for -: 'Timestamp' and 'str'